### PR TITLE
Made program classier, more selfish, fixed setup

### PR DESCRIPTION
**Pull request by theJalden**
Made the program a class, run the  program if python file is run.  Got
rid of infinite while tool in setup, fixed input into self.robots(index
was wrong).  Remove last entry in self.robots if yn is 'n'.  Added a ":
" after areas asking for user input for readability.

### CODE REVIEW

**Comment by theJalden** [comment]
Hey, I just need to know if you plan on commiting these changes

**Comment by cougarTech2228** [comment]
i have been redoing the program structure into modules 
so i wont merge this fork
but i will use it for reference
thanks for your help

**Comment by cougarTech2228** [comment]
once the pit scouting and match scouting apps are ready to integrate we can merge them manually

**Comment by cougarTech2228** [comment]
merging a fork is called a pull request
but pulling repository changes to your local and working repositories is also called a pull
very confusing

**Pull request closed without merging**
